apiVersion: v1
kind: Service
metadata:
  name: api-ml-vestuario
  labels:
    name: api-ml-vestuario
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: api-ml-vestuario
